type = "agent"
public = true
region = "${BL_REGION:us-pdx-1}"

[runtime]
generation = "mk3"
memory = 4096
minScale = 1

[[volumes]]
name = "openclaw-volume"
mountPath = "/root/.openclaw"

[build]
slim = false
