#!/bin/bash
set -e

export PATH="$(npm prefix -g)/bin:$PATH"

PORT="${PORT:-80}"
OPENCLAW_PORT="8080"
HOST="${HOST:-0.0.0.0}"
export OPENCLAW_HOME="${OPENCLAW_HOME:-/root}"
OPENCLAW_DIR="$OPENCLAW_HOME/.openclaw"
OPENCLAW_CONFIG="$OPENCLAW_DIR/openclaw.json"
SETUP_CONFIG="$OPENCLAW_DIR/setup-config.json"
ENV_FILE="$OPENCLAW_DIR/env"

mkdir -p "$OPENCLAW_DIR" "$OPENCLAW_DIR/workspace"

# Ensure plugin is installed (may be missing if .openclaw is volume-mounted)
if ! openclaw plugins list 2>/dev/null | grep -q "openclaw-blaxel-sandbox"; then
  echo "Plugin openclaw-blaxel-sandbox not found, installing..."
  openclaw plugins install /opt/openclaw-blaxel
  openclaw plugins enable openclaw-blaxel-sandbox
fi

# Fix ownership and permissions for volume-mounted plugin files
chown -R root:root "$OPENCLAW_DIR/extensions" 2>/dev/null || true
chmod -R go-w "$OPENCLAW_DIR/extensions" 2>/dev/null || true

# Migrate old config file name if present
if [ -f "$OPENCLAW_DIR/proxy-auth.json" ] && [ ! -f "$SETUP_CONFIG" ]; then
  mv "$OPENCLAW_DIR/proxy-auth.json" "$SETUP_CONFIG"
fi

# --- Load persistent env file from volume (written by setup or previous run) ---
if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
  echo "Loaded env from $ENV_FILE"
fi

# --- Resolve configuration ---
# Priority: 1) env vars  2) stored setup config  3) first-run setup wizard
PROXY_USER="${PROXY_USER:-}"
PROXY_PASSWORD="${PROXY_PASSWORD:-}"
MODEL="${OPENCLAW_MODEL:-}"

load_from_setup_config() {
  if [ -f "$SETUP_CONFIG" ]; then
    [ -z "$MODEL" ] && MODEL=$(jq -r '.model // empty' "$SETUP_CONFIG")
    [ -z "$PROXY_USER" ] && PROXY_USER=$(jq -r '.username // empty' "$SETUP_CONFIG")
    [ -z "$PROXY_PASSWORD" ] && PROXY_PASSWORD=$(jq -r '.password // empty' "$SETUP_CONFIG")

    SAVED_ENV_VAR=$(jq -r '.apiKeyEnvVar // empty' "$SETUP_CONFIG")
    SAVED_API_KEY=$(jq -r '.apiKey // empty' "$SETUP_CONFIG")
    if [ -n "$SAVED_ENV_VAR" ] && [ -n "$SAVED_API_KEY" ]; then
      CURRENT_VAL=$(eval echo "\${$SAVED_ENV_VAR:-}")
      if [ -z "$CURRENT_VAL" ]; then
        export "$SAVED_ENV_VAR=$SAVED_API_KEY"
      fi
    fi

    # Load Blaxel credentials from setup config if not already set
    if [ -z "$BL_WORKSPACE" ]; then
      SAVED_BL_WS=$(jq -r '.blWorkspace // empty' "$SETUP_CONFIG")
      [ -n "$SAVED_BL_WS" ] && export BL_WORKSPACE="$SAVED_BL_WS"
    fi
    if [ -z "$BL_API_KEY" ]; then
      SAVED_BL_KEY=$(jq -r '.blApiKey // empty' "$SETUP_CONFIG")
      [ -n "$SAVED_BL_KEY" ] && export BL_API_KEY="$SAVED_BL_KEY"
    fi
    return 0
  fi
  return 1
}

load_from_setup_config && echo "Loaded setup config from $SETUP_CONFIG"

# Determine what's needed for setup wizard
# On Blaxel (BL_CLOUD=true): only need model
# Off Blaxel: need model + credentials
NEEDS_SETUP="false"
if [ -z "$MODEL" ]; then
  NEEDS_SETUP="true"
elif [ "$BL_CLOUD" != "true" ] && { [ -z "$PROXY_USER" ] || [ -z "$PROXY_PASSWORD" ]; }; then
  NEEDS_SETUP="true"
fi

if [ "$NEEDS_SETUP" = "true" ]; then
  echo "============================================"
  echo "First-time setup required."
  echo "Visit http://$HOST:$PORT to configure."
  echo "============================================"

  AUTH_FILE="$SETUP_CONFIG" PORT="$PORT" node /setup-server.js

  if load_from_setup_config; then
    echo "Configuration saved. Starting OpenClaw..."
  else
    echo "Setup was not completed. Exiting."
    exit 1
  fi
fi

# Fallback model
MODEL="${MODEL:-anthropic/claude-sonnet-4-5}"

# --- Persist resolved config to volume ---
# Write env file so API keys and overrides survive restarts
{
  echo "# Auto-generated by OpenClaw entrypoint - do not edit manually"
  echo "OPENCLAW_MODEL=\"$MODEL\""
  [ -n "$PROXY_USER" ] && echo "PROXY_USER=\"$PROXY_USER\""
  [ -n "$PROXY_PASSWORD" ] && echo "PROXY_PASSWORD=\"$PROXY_PASSWORD\""
  # Persist any provider API key
  for KEY_VAR in ANTHROPIC_API_KEY OPENAI_API_KEY GEMINI_API_KEY BL_API_KEY BL_WORKSPACE; do
    KEY_VAL=$(eval echo "\${$KEY_VAR:-}")
    if [ -n "$KEY_VAL" ]; then
      echo "${KEY_VAR}=\"${KEY_VAL}\""
    fi
  done
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "Persisted configuration to $ENV_FILE"

# --- Compute allowed origins ---
if [ -z "$OPENCLAW_ALLOWED_ORIGIN" ] && [ -n "$BL_NAME" ] && [ -n "$BL_WORKSPACE_ID" ]; then
  if [ "$BL_ENV" = "dev" ]; then
    RUN_URL="runv2.blaxel.dev"
  else
    RUN_URL="bl.run"
  fi
  WS_ID=$(echo "$BL_WORKSPACE_ID" | tr '[:upper:]' '[:lower:]')
  ORIGIN_BASE="agt-${BL_NAME}-${WS_ID}"
  ORIGIN_GLOBAL="https://${ORIGIN_BASE}.${RUN_URL}"
  if [ -n "$BL_REGION" ]; then
    ORIGIN_REGIONAL="https://${ORIGIN_BASE}.${BL_REGION}.${RUN_URL}"
  fi
fi

# Build allowed origins list
ORIGINS_LIST=""
USE_HOST_HEADER_FALLBACK="false"
if [ -n "$OPENCLAW_ALLOWED_ORIGIN" ]; then
  ORIGINS_LIST="\"$OPENCLAW_ALLOWED_ORIGIN\""
elif [ -n "$ORIGIN_GLOBAL" ]; then
  ORIGINS_LIST="\"$ORIGIN_GLOBAL\""
  [ -n "$ORIGIN_REGIONAL" ] && ORIGINS_LIST="$ORIGINS_LIST, \"$ORIGIN_REGIONAL\""
else
  # Local/dev: external port may differ from internal (e.g. Docker port mapping),
  # so allow origin based on the Host header the browser sends
  USE_HOST_HEADER_FALLBACK="true"
fi
ORIGINS="[$ORIGINS_LIST]"

# --- Write OpenClaw config ---
if [ ! -f "$OPENCLAW_CONFIG" ]; then
  echo '{}' > "$OPENCLAW_CONFIG"
fi

cp "$OPENCLAW_CONFIG" "$OPENCLAW_CONFIG.bak" 2>/dev/null || true

TMP_CONFIG="$(mktemp)"

BL_API_KEY="${BL_API_KEY:-}"
BL_WORKSPACE="${BL_WORKSPACE:-}"

jq \
  --arg workspace "$OPENCLAW_DIR/workspace" \
  --arg model "$MODEL" \
  --argjson origins "$ORIGINS" \
  --argjson hostFallback "$USE_HOST_HEADER_FALLBACK" \
  --arg blApiKey "$BL_API_KEY" \
  --arg blWorkspace "$BL_WORKSPACE" \
  '
  .gateway = {
    mode: "local",
    reload: { mode: "hot" },
    auth: {
      mode: "trusted-proxy",
      trustedProxy: {
        userHeader: "X-Forwarded-User"
      }
    },
    trustedProxies: ["127.0.0.1/8", "172.16.0.0/12", "10.0.0.0/8"],
    controlUi: (
      if $hostFallback then
        { dangerouslyAllowHostHeaderOriginFallback: true }
      else
        { allowedOrigins: $origins }
      end
    )
  }
  | .plugins = (.plugins // {})
  | .plugins.allow = ["openclaw-blaxel-sandbox"]
  | .plugins.entries = (.plugins.entries // {})
  | .plugins.entries["openclaw-blaxel-sandbox"] = (.plugins.entries["openclaw-blaxel-sandbox"] // {})
  | .plugins.entries["openclaw-blaxel-sandbox"].enabled = true
  | if ($blApiKey != "" and $blWorkspace != "") then
      .plugins.entries["openclaw-blaxel-sandbox"].config = (
        (.plugins.entries["openclaw-blaxel-sandbox"].config // {})
        | .blaxel = { workspace: $blWorkspace, apiKey: $blApiKey }
      )
    else . end
  | .agents = (.agents // {})
  | .agents.defaults = (.agents.defaults // {})
  | .agents.defaults.workspace = $workspace
  | .agents.defaults.model = (.agents.defaults.model // {})
  | .agents.defaults.model.primary = $model
  ' \
  "$OPENCLAW_CONFIG" > "$TMP_CONFIG"

mv "$TMP_CONFIG" "$OPENCLAW_CONFIG"

echo "============================================"
echo "OpenClaw Gateway starting on localhost:$OPENCLAW_PORT"
if [ "$BL_CLOUD" = "true" ] && [ -z "$PROXY_USER" ] && [ -z "$PROXY_PASSWORD" ]; then
  echo "Auth: Blaxel OAuth2"
else
  echo "Auth: Basic auth (user: $PROXY_USER)"
fi
echo "Auth proxy listening on $HOST:$PORT"
echo "Model: $MODEL"
echo "Allowed Origins: $ORIGINS"
echo "============================================"

# Start auth proxy in the background
COOKIE_SECRET="${COOKIE_SECRET:-$(head -c 32 /dev/urandom | xxd -p | tr -d '\n')}"
export COOKIE_SECRET BL_CLOUD BL_ENV PORT UPSTREAM_PORT="$OPENCLAW_PORT"
export PROXY_USER PROXY_PASSWORD
node /auth-proxy.js &
PROXY_PID=$!

cleanup() {
  kill $PROXY_PID 2>/dev/null || true
  pkill -9 -f "openclaw gateway" 2>/dev/null || true
  exit 0
}
trap cleanup SIGTERM SIGINT

MAX_RETRIES="${MAX_RETRIES:-5}"
RETRY_COUNT=0

while true; do
  pkill -9 -f "openclaw gateway" 2>/dev/null || true
  sleep 1

  rm -f "$OPENCLAW_DIR"/*.lock "$OPENCLAW_DIR"/*.pid 2>/dev/null || true
  rm -f /tmp/openclaw/*.lock /tmp/openclaw/*.pid 2>/dev/null || true

  fuser -k "$OPENCLAW_PORT/tcp" 2>/dev/null || true
  sleep 0.5

  openclaw gateway \
    --port "$OPENCLAW_PORT" \
    --bind lan \
    --auth trusted-proxy \
    --force \
    --allow-unconfigured \
    --verbose
  EXIT_CODE=$?

  if [ $EXIT_CODE -eq 0 ]; then
    RETRY_COUNT=0
  else
    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "OpenClaw exited with code $EXIT_CODE (failure $RETRY_COUNT/$MAX_RETRIES)"
    if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
      echo "Max retries reached, giving up."
      cleanup
    fi
  fi

  echo "Restarting..."
done
